context.properties = {
    log.level = 2,
    default.clock.min-quantum = 64,
    default.clock.quantum = 256,
    default.clock.max-quantum = 2048,
    default.clock.rate = 48000,
    default.clock.allowed-rates = [ 48000 96000 ],
    support.dbus = true
  }

stream.properties = {
    resample.quality = 10
    node.latency = "256/48000"
}

# context.modules = [
#{   name = libpipewire-module-rt
#     args = {
#       	  nice.level = -11
#          rt.prio = 88
#          rlimits.enabled = false
#          rtportal.enabled = true
#          rtkit.enabled = false

#    }
#    flags = [ ifexists nofail ]
#}
#]