context.properties = {
    log.level = 2,
    default.clock.min-quantum = 256,
    default.clock.quantum = 512,
    default.clock.max-quantum = 2048,
    default.clock.rate = 48000,
    default.clock.allowed-rates = [ 48000 96000 ],
    support.dbus = true
  }

stream.properties = {
    resample.quality = 10
    node.latency = "256/48000"
}

context.modules = [
{   name = libpipewire-module-rt
    args = {
        #nice.level   = 20
        #rt.prio      = 88
        #rt.time.soft = -1
        #rt.time.hard = -1
        rlimits.enabled = false
        #rtportal.enabled = true
        rtkit.enabled = true
        #uclamp.min = 0
        #uclamp.max = 1024
    }
    flags = [ ifexists nofail ]
}
]