"context.modules" = [
{ name = libpipewire-module-filter-chain
    args = {
        node.name        = "effect_input.rnnoise"
            node.description = "Filtered Q2U"
            media.name       = "Filtered Q2U"
            filter.graph = {
                nodes = [
		{ type = lv2
		  name = gate
		  plugin = "http://lsp-plug.in/plugins/lv2/gate_stereo"
		  control = {
		  	  gt = 0.001
			  at = 5.0
			  rt = 50
                  } 
		}
                    { type = lv2
                    name = compress
                    plugin = "http://lsp-plug.in/plugins/lv2/compressor_stereo"
                    control = {
                        al = 0.003981071705534969 # threshhold
                        at = 12     # attack time
                        kn = 0.25  # knee
                        rt = 250 # release time
                        cr = 4 # ratio
                        mk = 4 # makeup gain
                    }
                }
            ]
            links = [
	    { output = "gate:out_l" input = "compress:in_l" }
	    { output = "gate:out_r" input = "compress:in_r" }
            #    { output = "rnnoise:Output (L)" input = "compress:Input L" }
            #    { output = "rnnoise:Output (R)" input = "compress:Input R" }
            ]
            inputs = [ "gate:in_l" "gate:in_r"]
            outputs = ["compress:out_l" "compress:out_r"]
        }
        audio.channels = 2
        audio.position = [ FL FR ]
        capture.props = {
            node.passive = true
            node.target    = "alsa_input.usb-Samson_Technologies_Samson_Q2U_Microphone-00.analog-stereo"
        }
        playback.props = {
            media.class = Audio/Source
        }
    }
}]
# 