"context.modules" = [
{ name = libpipewire-module-filter-chain
    args = {
        node.name        = "effect.rnnoise"
        node.description = "Filtered Q2U"
        media.name       = "Filtered Q2U"
        filter.graph = {
        nodes = [
	{ type = builtin
	  name = mixer
	  label = mixer
	  control = { "Gain 1" = 1.0 "Gain 2" = 1.0 }
	}
        { type = ladspa
          name = rnnoise
          plugin = "rnnoise_ladspa"
          label  = "nt-filter"
          control = {
              #"VAD %%" = 0
          }
        }
        { type = lv2
          name = compress
          plugin = "http://lsp-plug.in/plugins/lv2/compressor_mono"
          control = {
	    al = 0.004 # threshhold
	    at = 12    # attack time
            kn = 0.25  # knee
            rt = 250   # release time
            cr = 4     # ratio
            mk = 4     # makeup gain
	  }
	}
	{ type = builtin
	  name = copyL
	  label = copy
	}
	{ type = builtin
	  name = copyR
	  label = copy
	}
	]
	links   = [
	{ output = "mixer:Out" input = "rnnoise:Input" }
	{ output = "rnnoise:Output" input = "compress:in" }
	{ output = "compress:out"   input = "copyL:In"  }
	{ output = "compress:out"   input = "copyR:In"  }
	]
        inputs  = [ "mixer:In 1" "mixer:In 2" ]
        outputs = [ "copyL:Out"  "copyR:Out"  ]
      }
      audio.channels = 2
      audio.position = [ FL FR ]
      capture.props = {
        node.passive = true
        node.target  = "alsa_input.usb-Samson_Technologies_Samson_Q2U_Microphone-00.analog-stereo"
      }
      playback.props = {
          media.class = Audio/Source
      }
    }
}]
# 