# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" "bcache" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/nvme0n1p3:/dev/sdc:/dev/sde";
      fsType = "bcachefs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/D147-EA04";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/65946d23-8ff5-4505-98bd-e9a039304d2c"; }
    ];

  fileSystems."/media/old/share" =
    { device = "/dev/disk/by-label/Share";
      fsType = "ntfs";
      options = [ "rw" "uid=1000" ];
    };

  fileSystems."/media/old/gamma" =
    { device = "/dev/disk/by-label/Gamma";
      fsType = "ntfs";
      options = [ "rw" "uid=1000" ];
    };

  fileSystems."/media/old/Windows" =
    { device = "/dev/disk/by-id/ata-Corsair_Neutron_XTI_SSD_163080960001203421AD-part2";
      fsType = "ntfs";
      options = [ "rw" "uid=1000" ];
    };
}
