# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];


  boot.zfs.extraPools = [ "tank" ];

  fileSystems."/" =
    { device = "tank/ROOT/nixos";
      fsType = "zfs";
    };

  fileSystems."/media" =
    { device = "tank/media";
      fsType = "zfs";
    };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/D147-EA04";
    fsType = "vfat";
    options = [
      "noatime"
      "nodiratime"
      "flush"
      "fmask=0077" "dmask=0077"
    ];
  };

  #fileSystems."/bcachefs" =
  #  {
  #    device = "UUID=927137d3-8864-4756-9c7e-3b9d1efff07b";
  #    fsType = "bcachefs";
  #    options = [
  #      "ro" 
  #      "errors=fix_safe"
  #      "noatime"
  #      "nodiratime"
  #      "journal_rewind_discard_buffer_percent=0"
  #    ];
  #  };

  fileSystems."/mnt" = {
    device = "/dev/disk/by-uuid/fd588396-85fe-49b0-a6bf-870008f59a60";
    fsType = "xfs";
    options = [ "noatime" ];
  };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/c10846b3-76c3-40e9-bd4e-fdf2fb127e0e"; }
      { device = "/dev/disk/by-uuid/65946d23-8ff5-4505-98bd-e9a039304d2c"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  networking.hostId = "30e0f448";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
