# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "ahci"
    "usbhid"
    "usb_storage"
    "sd_mod"
    "crc32c"
    "bcachefs"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  fileSystems."/" =
    {
      device = "UUID=927137d3-8864-4756-9c7e-3b9d1efff07b";
      fsType = "bcachefs";
      options = [
        "ro" 
        "errors=fix_safe"
        "noatime"
        "nodiratime"
        "journal_rewind_discard_buffer_percent=0"
      ];
    };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/D147-EA04";
    fsType = "vfat";
    options = [
      "noatime"
      "nodiratime"
      "flush"
    ];
  };

  fileSystems."/mnt" = {
    device = "/dev/disk/by-uuid/fd588396-85fe-49b0-a6bf-870008f59a60";
    fsType = "xfs";
    options = [ "noatime" ];
  };

  fileSystems."/mnt/boot" = {
    device = "/dev/disk/by-uuid/A0DC-9A9E";
    fsType = "vfat";
  };

  fileSystems."/home/daniel/.local/share/Steam/steamapps/common/.inodes32_mnt" = {
    device = "/home/daniel/.local/share/Steam/steamapps/common/.inodes32_xfs";
    fsType = "xfs";
    options = [ "inode32,noatime" ];
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/65946d23-8ff5-4505-98bd-e9a039304d2c"; }
  ];

}
