# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "tank/ROOT/nixos";
      fsType = "zfs";
    };

  fileSystems."/media" =
    { device = "tank/media";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/E717-B5ED";
      fsType = "vfat";
      options = [
        "noatime"
        "nodiratime"
        "flush"
        "fmask=0077" "dmask=0077"
      ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/2bbb625a-6a54-418f-86b7-c73b1d583ba0"; }
      { device = "/dev/disk/by-uuid/85a8a5ee-13f6-4b87-b6cb-5c59e47ebebb"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  networking.hostId = "c7a8f482";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  # can't swraid /boot
  # boot.swraid.enable = true;
}
